#1
print('30\tdays\tof\tpython')
#2
print('coding\tfor\tall')
#3
company=('Coding\tFor\tAll')
#4
print(company)
#5
print(len(company))
#6
print(company.upper())
#7
print(company.lower())
#8
print(company.capitalize())
print(company.title())
print(company.swapcase())
#9
print(company[0:6])
#10
print(company.index('Coding'))
#11
print(company.replace('Coding' , 'python'))
#12
